### PR TITLE
Update main_program.pyw

### PR DESCRIPTION
**Pull request by vickkie**
An  update on the python program to inform on charger disconnected

### CODE REVIEW

**Comment by vickkie** [comment]
This helps in notifying and takes action if user does not connect..

**Comment by vickkie** [comment]
An  update on the python program to inform on charger disconnected
Check if it improved
includes an bundled Application and Installer

**Comment by inboxsgk** [comment]
> An update on the python program to inform on charger disconnected Check if it improved includes an bundled Application and Installer

Hi, I just reviewed your code, there are good additions to the program. I believe your addition of keeping an icon in the taskbar tray will make it easier to enable and disable the bot as you prefer. 

I'm using notify-py as it is supported across platforms like Linux and Mac OS aswell.

PS~ My suggestion for you is to change auto shutdown feature with hibernation so that user workflows can be continued.

**Comment by vickkie** [comment]
Hi, thanks for your reply.
Good thing you  highlighted the shutdown issue, i never thought of it .
I will update the code and inform you on the update ASAP.
Any other idea on improving code is welcome too,you can notify me

**Comment by vickkie** [comment]
Several update done
-  hibernation fixed to work cross platform
- Can run on cross platform
- Several improvements added
- Update on all executables for windows 

In case of any issues. Notify. Improvements will continue

**Pull request closed without merging**
